### ISSUE TITLE
MPlayer name decision

### ISSUE THREAD

**Issue by JOJ0** [nihaalnz/MPlayer#1]
Hi,
I just want to point out that you might want to reconsider using the name MPlayer for your fairly new project to avoid confusion in the future. There is an Open Source music player around for years that is still under active development: https://en.wikipedia.org/wiki/MPlayer

Also it is spelled exactly as your repo. Just a heads up that maybe now is still time to find a better name.

HTH :)
Jojo

**Comment by delrius-euphoria** [comment]
That is true, I did not give much thought into the name or rather look it up. Thanks for letting me know, ill change it in the next update.

**Comment by delrius-euphoria** [comment]
Changed name to resolve conflict
